### ISSUE TITLE
armhf + clang-9 test failure

### ISSUE THREAD

**Issue by mr-c** [simd-everywhere/simde#622]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=971429 
https://ci.debian.net/data/autopkgtest/testing/armhf/s/simde/7230347/log.gz

```
/usr/bin/clang++ -g -rdynamic CMakeFiles/run-tests.dir/run-tests.c.o CMakeFiles/run-tests.dir/x86/run-tests.c.o CMakeFiles/run-tests.dir/arm/run-tests.c.o CMakeFiles/run-tests.dir/arm/neon/run-tests.c.o -o run-tests  libmunit.a -lm libsimde-test-native.a libsimde-test-emul.a 
libsimde-test-native.a(avx512f.c.o): in function `test_simde_mm512_abs_epi32':
/tmp/autopkgtest-lxc.af0q6pib/downtmp/autopkgtest_tmp/test/x86/avx512f.c:103:(.text+0x18fe8): relocation truncated to fit: R_ARM_CALL against `simde_test_x86_assert_equal_i32x16_'
```

**Comment by nemequ** [comment]
I think this is due to the tests being a single giant executable when using CMake.  The easy fix would be to use Meson instead.

A more difficult fix would be to switch CMake to build the tests the same way Meson does; obviously the code is already in place to do that, so it wouldn't be *too* difficult.  The problem is we would have to figure out how to get the various emulators set up to work with CTest… we've been avoiding the issue by just running `run-tests` manually, but with this you wouldn't have just the one executable, but several hundred (currently 702).

**Comment by mr-c** [comment]
Seems to be working in v0.7.0-rc.1 (I'm also going to switch to meson+ninja for testing in Debian)
