### ISSUE TITLE
Missing instructions for SSE?

### ISSUE THREAD

**Issue by jdumas** [simd-everywhere/simde#650]
Hi,

It looks like simde has `_mm_loadu_si128` implemented in `x86/sse2.h`, but it looks like the following are still missing, even though they are part of SSE/SSE2:
- `_mm_loadu_si16`
- `_mm_loadu_si32`
- `_mm_loadu_si64`
- `_mm_storeu_si16`
- `_mm_storeu_si32`
- `_mm_storeu_si64`

**Comment by nemequ** [comment]
Thanks :)

It looks like they're new functions… clang added them in 8.0, GCC in 11 (i.e., not yet in a release). PGI doesn't have them at all. MSVC has had them since at least 2017 (the oldest version I have installed in my Windows VM), so that's probably where they came from.

I'll add them to SIMDe in a bit.
