### ISSUE TITLE
docker-testing: clang-8 no longer in Debian testing/unstable as of 2020-11-08

### ISSUE THREAD

**Issue by mr-c** [simd-everywhere/simde#666]
https://tracker.debian.org/news/1190845/removed-1801-10-from-unstable/

**Comment by nemequ** [comment]
AFAIK this shouldn't really be an issue since 527847328cfdff5f6e76b10fb91ecbfb364751a3; we don't hard-code the package names, just install all the clang versions we find.  That way we also don't need one Dockerfile per release.  It really just means that I'm a lot less likely to test something on clang-8 in the Docker env.  CI shouldn't really change either since it's all using Ubuntu instead of Debian…

Is it breaking something for you?

**Comment by mr-c** [comment]
Ah, this occured due to a partial rebuild of the images after a recent change was made to the Dockerfile.

**Comment by nemequ** [comment]
I noticed that there was still a cross file for clang-8 instead of clang-11, I'll switch that over.

Long term we really need to generate the cross files based on the installed compilers, but that's actually fairly complicated because we need to do different things on different architectures, compilers, versions, etc., and sometimes we want multiple builds (e.g., one using -march=native, one use -march=skylake server [or whatever] and going through SDE.
