### ISSUE TITLE
Automatic instruction performance evaluation tool / script

### ISSUE THREAD

**Issue by wuye0109** [simd-everywhere/simde#668]
Currently the evaluation on instruction convert is quite hard. 
The way in dogbolt is good, but just can do one or several instructions at a time and need lots of code writting. 
Would suggest to develop a script to do some kind of automatic way of compile and count the asm insts. This should help a lot and provide ideas on initial performance of the instructions.

**Comment by mr-c** [comment]
Thanks @wuye0109 ! Yes, even a one-time report sorted by the number of instructions generated for a large number of compiler and build option combinations would be very useful to highlight places to optimize.

An automated check for every PR would be even better! We would be able to catch regressions and evaluate new instruction implementations much more easily than we do now.

**Comment by nemequ** [comment]
This sounds a lot like #349, maybe we should close this in favor of that issue?

That issue is a lot more ambitious, but the first part is basically what you've described above.  Note that it's not just the instruction count we need to be concerned about; some instructions are much more expensive than others.  Raw instruction count correlates to performance, but it's not a hard rule.  LLVM MCA should provide much more accurate estimates.

While this would be really nice to have, I don't think this is something that I'll have time to get to in the foreseeable future.

**Comment by nemequ** [comment]
This sounds a lot like #349, maybe we should close this in favor of that issue?

That issue is a lot more ambitious, but the first part is basically what you've described above.  Note that it's not just the instruction count we need to be concerned about; some instructions are much more expensive than others.  Raw instruction count correlates to performance, but it's not a hard rule.  LLVM MCA should provide much more accurate estimates.

While this would be really nice to have, I don't think this is something that I'll have time to get to in the foreseeable future.

**Comment by wuye0109** [comment]
Yes, just look at #349, this topic is already discussed and it is same thing. So closed this issue and we can direct to #349 for this idea.
