### ISSUE TITLE
GitHub Actions + macOS 10.3 

### ISSUE THREAD

**Issue by mr-c** [simd-everywhere/simde#669]
```
Run meson setup build -Db_coverage=true
  meson setup build -Db_coverage=true
  shell: /bin/bash -e {0}
  env:
    DEVELOPER_DIR: /Applications/Xcode_10.3.app
The Meson build system
Version: 0.56.0
Source dir: /Users/runner/work/simde/simde
Build dir: /Users/runner/work/simde/simde/build
Build type: native build
Project name: SIMDe
Project version: 0.7.0-rc.1

meson.build:1:0: ERROR: Compiler cc can not compile programs.
```

https://github.com/simd-everywhere/simde/pull/667/checks?check_run_id=1577256946#step:6:16

**Comment by nemequ** [comment]
I don't see that error at the like you posted; maybe it was just a temporary issue, and re-running the build resolved the issue?  I do occasionally see things like xcode failing to install (usually due to something like a network issue or a server being down).

**Comment by mr-c** [comment]
We don't normally build with xcode 10.3, but I tried it out as the clang version is quite different.

**Comment by nemequ** [comment]
Okay, then this isn't really a SIMDe problem, it's a broken/misconfigured xcode installation.  I suppose a meson issue is also possible, but that seems unlikely since from its perspective there isn't really anything different between xcode 10.3 and 11.4.  I'd need to see the error log (`$BUILDDIR/meson-logs/meson-error.log`, or maybe `meson-errors.log`, something like that…) to see exactly what the problem is, but if `cc` can't compile programs at that point it's almost certainly a broken install.

**Comment by nemequ** [comment]
/me is going to close, but feel free to re-open if you disagree… just keep in mind that I don't really have good access to a macOS machine to test on; I'd need to use CI to debug :(
