### ISSUE TITLE
x_mm_abs_ps and similar, lots of problems

### ISSUE THREAD

**Issue by jpcima** [simd-everywhere/simde#704]
Using simde `v0.7.2`, clang 11.0.1, gcc 10.2.0

---
1. `x_mm_abs` intrinsics don't always produce efficient code on SSE

In these cases, the generic path is taken in both functions `simde_x_mm_abs_ps` / `simde_vabsq_f32`.
- Under `clang -O3`, the `x_mm_abs_ps` produces an inefficient chunk of a dozen insns
- Under `clang -O3`, the equivalent `simde_vabsq_f32` manages to reduce to a single insn, surprisingly
- Under `gcc`, the efficient code is obtained in `-O3` only, `-O2` produces a large chunk

A candidate implementation, masking the sign bit, might be
```
    union { uint32_t u32; float f32; } u_;
    u_.u32 = UINT32_C(0x7FFFFFFF);
    return _mm_and_ps(_mm_set1_ps(u_.f32), a);
```
It reduces to the single `ANDPS` instruction. It can replace the `AVX512F_NATIVE` one.

---
 2. Similar remarks apply to `m128d` variant `simde_x_mm_abs_pd`, but as well:

 - NEON and Altivec implementations are looking extremely suspicious. (don't have hw to check)
eg. `r_.neon_f32 = vabsq_f32(a_.neon_f32)`

Applied on 32bit floats, the operation would mask out 4 sign bits rather that 2, which likely results in zeroing 2 innocent bits.

- Similar to above, one may provide a candidate `pd` implementation with use of SSE only
by reinterpreting the register as a `m128` and perform `ANDPS` with an alternance of bitmasks `(0xFFFFFFFF, 0x7FFFFFFF, 0xFFFFFFFF, 0x7FFFFFFF)`.

**Comment by rosbif** [comment]
> A candidate implementation, masking the sign bit, might be
> 
> ```
>     union { uint32_t u32; float f32; } u_;
>     u_.u32 = UINT32_C(0x7FFFFFFF);
>     return _mm_and_ps(_mm_set1_ps(u_.f32), a);
> ```

Rather than passing via a union, which is dodgy if you follow the C standard strictly, maybe someting like this would be better (untested);
`return _mm_and_ps(_mm_castsi128_ps(_mm_set1_epi32(INT32_MAX)), a);`

**Comment by rosbif** [comment]
And for the 64-bit one something like (again untested):
return _mm_and_pd(_mm_castsi128_pd(_mm_set1_epi64x(INT64_MAX)), a);

**Comment by jpcima** [comment]
I've added this to PR #705
There's an issue to this implementation though, it can't build on SSE1 only with GCC, because intrinsics `_mm_castsi128_ps` and `_mm_set1_epi32` are listed as SSE2.

**Comment by aqrit** [comment]
is `_mm_set1_ps(-0.0f)` non-portable?

**Comment by jpcima** [comment]
It is portable yes, unfortunately gcc seems to produce worse code based on it.
https://godbolt.org/z/5WMKGq

**Comment by nemequ** [comment]
The union isn't, though ☹.  Technically it is undefined behavior; once you access one element of a union you're not allowed to access the same object via a different element.  It's not generally a problem on x86, but I've run into this on other platforms (like Arm) pretty often.  On GCC and clang, I believe you can use the `may_alias` attribute to make this safe, but that's not portable to other compilers.

The right thing to do here is actually to use `memcpy` (well, `simde_memcpy`) to copy the data from the `uint32_t` to a `simde_float32`. That takes care of the aliasing issues, and basically any vaguely modern compiler [should optimize it away](https://godbolt.org/z/5cvjhE).

We do have some utility functions in simde-f16.h to convert from uint32_t to simde_float32, so this could just be `_mm_and_ps(_mm_set1_ps(simde_float32_reinterpret_u32(UINT32_C(0x7fffffff))), a);` if you include simde-f16.h.

As for `simde_x_mm_abs_pd`, yes, those should definitely be 64 instead of 32, and the tests should be for A64V8 and POWER8.  I'm impressed this made it through CI… probably because we use relatively small numbers (-1000, 1000) in the test cases so those bits are always zero :(.

**Comment by jpcima** [comment]
> I'm impressed this made it through CI…

I identified the reason why, and it's this:
`simde_test_x86_assert_equal_f64x2(r, simde_mm_loadu_pd(test_vec[i].r), 1);`

With the precision argument set to 1, it's compared with maximum error 0.1 (1e-1), which lets the mantissa error pass through easily. Change to 10, and it will detect.

**Comment by jpcima** [comment]
Very appreciated, thanks!
