### ISSUE TITLE
simde_mm_movemask_epi8 in A32V7 and A64V8

### ISSUE THREAD

**Issue by stophin** [simd-everywhere/simde#710]
Armv8 has both SIMDE_ARM_NEON_A32V7_NATIVE and SIMDE_ARM_NEON_A64V8_NATIVE defined, and in simde_mm_movemask_epi8 function in armv8 case, the conditional compilation order is A64V8 then A32V7, so it is compiled as A64V8, though tests show that the intrinsic in A32V7 is slightly faster than that in A64V8. 
Although, I don't quite understand using vreinterpret_xxx here.  vreinterpret_xxx contains a memcpy here. It can totally be replaced by type cast, say, 
-      uint32x4_t paired16 = vreinterpretq_u32_u16(vsraq_n_u16(high_bits, high_bits, 7));
+      uint32x4_t paired16 = (uint32x4_t)(vsraq_n_u16(high_bits, high_bits, 7));
but tests show that there's no significant speed up when change memcpy to type cast. (maybe memcpy is a macro replaced by __builtin_memcpy?)

**Comment by nemequ** [comment]
Interesting, thanks. I'll remove the AArch64 implementation in a bit; looking at the instructions I doubt it would be any faster even with a CPU with a fast addv.

As for the use of `vreinterpret_xxx`, compilers are very good about handling memcpy (and yes, the compiler will use `__builtin_memcpy` there, though `memcpy` isn't a macro).  We actually use memcpy (via [`simde_memcpy`](https://github.com/simd-everywhere/simde/blob/107fab8cf29c36506e8b5b98629eb909043cbefb/simde/simde-common.h#L556-L644)) a *lot* internally…

While a cast would work on GCC/clang, that's actually only because `uint32x4_t` is implemented using [vector extensions](https://gcc.gnu.org/onlinedocs/gcc/Vector-Extensions.html).  In other words, it's a compiler extension which may not be supported by other compilers.

The `vreinterpret*` functions are a bit like `_mm_cast*` on x86; they don't actually generate any code, but are instead used to safely convert from one vector type to another.  If you want some documentation, the [Operations on data types](https://developer.arm.com/documentation/101028/0012/13--Advanced-SIMD--Neon--intrinsics?lang=en#operations-on-data-types) section of the ACLE documentation, which addresses this.

**Comment by stophin** [comment]
@nemequ  Thank you for your explanation.  Very clear narrative and thanks for the time. It resolved my problem, otherwise I would 
 have to read the doc line by line.  I doubt if there's any faster implenmentation for simde_mm_movemask_epi8, or maybe it can only be accelerated by cpu intrinsics.
