### ISSUE TITLE
Excess elements in vector initializer when compiling NEON to SSE

### ISSUE THREAD

**Issue by ngzhian** [simd-everywhere/simde#751]
https://godbolt.org/z/YWPKT88se

```
#define SIMDE_ENABLE_NATIVE_ALIASES
#include <https://simde.netlify.app/amalgamated/arm/neon.h>

uint8_t foo(uint8x16_t a) {
    return vgetq_lane_u8(a, 1);
}
int main() {
  uint8x16_t x = {1,2,3,4,5,6,7,8,1,2,3,4,5,6,7,8};
  return foo(x);
}
```

compile with x86-64 `clang -O3`:

```
<source>:7:23: error: excess elements in vector initializer
  uint8x16_t x = {1,2,3,4,5,6,7,8,1,2,3,4,5,6,7,8};
                      ^
1 error generated.
Compiler returned: 1
```

Compiling with ARM64 gcc works fine.

**Comment by ngzhian** [comment]
Hm, I guess it's because `uint8x16_t` is another name for `__m128i`, which at least on clang is in emmintrin.h: `typedef long long __m128i __attribute__((__vector_size__(16), __aligned__(16)));` and thus only take 2 elements in the initializer list.

Is there a way to work around this?

**Comment by nemequ** [comment]
That code isn't actually standard NEON. It only works on GCC and clang due to being implemented using [GCC-style vector extensions](https://gcc.gnu.org/onlinedocs/gcc/Vector-Extensions.html). See [Arm C Language Extensions Documentation](https://documentation-service.arm.com/static/5f7b826ed3be967f7be46d22?token=) § 13.1.8, which mentions this issue specifically:

> ACLE does not define static construction of vector types. E.g.
>
> `int32x4_t x = { 1, 2, 3, 4 };`
>
> Is not portable. Use the vcreate or vdup intrinsics to construct values from scalars.

For example, I believe this will also fail on MSVC.

Unfortunately, Arm doesn't really make this easy. Your best bet is probably something like https://godbolt.org/z/oYh7sdobe:

```c
  uint8_t xa[] = { 1,2,3,4,5,6,7,8,1,2,3,4,5,6,7,8 };
  uint8x16_t x = vld1q_s8(xa);
```

**Comment by ngzhian** [comment]
Oh nice, thanks for pointing that chapter of that document. I did not know about this non-portability. It is unfortunate that we have to use a load instruction, but from the godbolt it looks possible to be optimized away. I will file an upstream issue to discuss this, thanks!

**Comment by mr-c** [comment]
@nemequ is there a wiki page we can collect these sorts of tips and documentation?

**Comment by nemequ** [comment]
The FAQ I guess? I don't think this is really frequently asked, though. We could start a new page, I suppose.
