### ISSUE TITLE
Amalgamated headers on netlify not working on Godbolt (compile to WebAssembly)

### ISSUE THREAD

**Issue by ngzhian** [simd-everywhere/simde#759]
Please see https://godbolt.org/z/asfaPs7KE

```
https://simde.netlify.app/amalgamated/arm/neon.h:37573:24: error: use of undeclared identifier 'fmaxf'
        r_.values[i] = fmaxf(a_.values[i], b_.values[i]);
```

Think maybe the hosted version just needs to be updated?

**Comment by ngzhian** [comment]
Hm, maybe this is a godbolt thing, math.h is provided by emscripten, and I think godbot uses plain clang++ without any emscripten.

**Comment by ngzhian** [comment]
On the other hand, we have detections like:

https://github.com/simd-everywhere/simde/blob/bdc869813d2d49ee45d28c1bd367b3b9a5982ff0/simde/arm/neon/maxnm.h#L49

that doesn't seem to be working when on godbolt.

**Comment by nemequ** [comment]
Hm, ti looks like that call is missing the `simde_math_` prefix, so it's trying to use `fmaxf` instead of `__builtin_fmaxf`.  Also, the `simde_math_f{min,max}{,f}` macros are messed up, they should take two parameters not three.

I'm testing a fix right now, though since I don't have a good way to test this locally it might take a few tries…

**Comment by nemequ** [comment]
It's working now. Thanks for the report!
