### ISSUE TITLE
Add arm64/ppc64le/s390x builds on Travis

### ISSUE THREAD

**Issue by junaruga** [simd-everywhere/simde#764]
Excellent news is coming. Now Travis `arch: arm64`, `arch: ppc64le` and `arch: s390x` have the free unlimited builds without consuming credits for every open repository again!

Here is the official document published today.
https://docs.travis-ci.com/user/billing-overview/#partner-queue-solution

Here is my note when working on the Ruby project to revive Travis.
If we do not want to consume the credits, it's good to avoid using `arch: amd64` in Travis, because it consumes credits.
https://bugs.ruby-lang.org/issues/17818#note-3

**Comment by nemequ** [comment]
That's great news, thanks!

>  If we do not want to consume the credits, it's good to avoid using arch: amd64 in Travis, because it consumes credits.

No problem, I have no interest in using Travis for x86 again; there are plenty of options for that.  I'm mostly interested in ppc64le and s390x since other providers don't offer those, though I might add an aarch64 build or two since our arm builds on drone are a bit limited.  Too bad they don't have SVE ☹.

**Comment by junaruga** [comment]
OK! We can run the native ppc64le/s390x CI. That's great.
By the way, what is SVE?

**Comment by junaruga** [comment]
As a reference, here is my repository to test the current Travis. The latest Ubuntu version is focal.
https://github.com/junaruga/ci-multi-arch-native-test/blob/master/.travis.yml

**Comment by junaruga** [comment]
Thanks for the explanation! It seems that the SVE is more advanced technology than Intel's fixed bit vectors.

**Comment by nemequ** [comment]
Not necessarily.  SVE certainly has its advantages, but so does AVX-512.  Overall, I'd say AVX-512 has more powerful instructions which you have to call multiple instructions on Arm to emulate.  If you're careful, you can probably create more optimized versions of your code on x86 than either NEON or SVE.

One of the biggest problems with the x86 SIMD iSA extensions, including AVX-512, is fragmentation.  For years Intel has been reserving AVX-512 support to its higher-end CPUs, and it shows.  According to the latest [Steam Hardware Survey](https://store.steampowered.com/hwsurvey), AVX-512F is only available on 1.17% of machines.  And that is machines with Steam installed; a pretty big bias in favor of faster, more powerful machines.  Only now is Intel starting to *announce* lower-end CPUs with AVX-512 support, and on the AMD side Zen 4 will be the first AMD CPUs to support AVX-512.

Even within AVX-512 there is a lot of fragmentation.  AVX-512F is the "base" AVX-512 instruction set, all the others are optional, and there are already a lot of options, including:

 * AVX-512BW
 * AVX-512VL
 * AVX-512CD
 * AVX-512DQ
 * AVX-512ER
 * AVX-512IFMA52
 * AVX-512PF
 * AVX-512VPOPCNTDQ
 * AVX-512_4FMAPS
 * AVX-512_4VNNIW
 * AVX-512_BF16
 * AVX-512_BITALG
 * AVX-512_VBMI
 * AVX-512_VBMI2
 * AVX-512_VNNI
 * AVX-512_VP2INTERSECT

The end result is that you often have to write several different versions of your code.  You'll probably want one that is limited to SSE2 (the baseline for x86_64), and one which supports up to SSE4.1 or SSE4.2 (which the [Steam Hadrware Survey](https://store.steampowered.com/hwsurvey) has at a bit north of 98% penetration right now).  Maybe you want something in between, maybe not; that probably depends on your userbase, how much of a performance boost you might be able to get, and how much time you're willing to invest in development, *etc.*.  You'll likely also want an AVX2 version, since that can be a pretty big performance boost and pretty good availability.  And then there is AVX-512; you'll probably want to start with something which requires AVX-512F and maybe AVX-512BW, then you might want something which also depends on some other extensions, again depending on how much of a performance gain you'll get and how much development time it would take.

And it's not like you can just define preprocessor macro in your code to easily switch between between calling `_mm_*`, `_mm256_*` and `_mm512_*` functions (unless you want to use SIMDe to emulate some functions).  There are lots of 128-bit instructions which aren't available until AVX or AVX-512, or later variants of SSE.  You really do need multiple versions.

With SVE, on the other hand, you can have one version of your code and it will work on any vector width.  One big advantage this gives Arm is that lower-end parts can still just have smaller vector units (i.e., 128-bit) whereas server or HPC parts can have much larger units (512-bits or beyond).  That's huge because Arm doesn't have to offer expensive (in terms of die size and power consumption) 512-bit vector units on low-end chips like Intel is starting to, yet programmers still don't have to write multiple versions.

SVE does have multiple versions; they're on SVE2 right now (AFAIK no hardware was ever built which only supports the original SVE), and there are some optional extensions within SVE/SVE2, so you may still end up switching between different versions.  It's not nearly as common as it is on x86, though, or as random (SVE either supports a feature or doesn't; you don't have to worry about it supporting something for 32-bit integers but not 16-bit, or unsigned versions being in a different extension from signed), and taking vector length out of that equation is a really big deal; different vector lengths pretty much multiplies the number of versions you might want on x86 by 3 (for 128, 256, and 512-bit vectors).

**Comment by junaruga** [comment]
I would close this ticket as I see the Travis adding ppc64le and s390x cases. Thanks!
https://github.com/simd-everywhere/simde/blob/master/.travis.yml
