### ISSUE TITLE
neon: Function signatures of load/store intrinsics disallow unaligned memory accesses

### ISSUE THREAD

**Issue by dreifachstein** [simd-everywhere/simde#939]
NEON supports unaligned load/store so such intrinsics should use `void*` instead of `T*`.

**Comment by nemequ** [comment]
You have a good point, but I'm not sure I agree with this.  If I were designing the API I'd probably have different intrinsics for unaligned loads/stores and *they* would take `void*`, but I'd definitely keep the aligned versions since they are usually what people would want.  Opting out of the type system by default means making it much easier to do something really wrong and not having the compiler warn you... I definitely want a warning if I try to pass a `float*` to `vld1q_f64` instead of `vld1q_f32`.

However, that's really a moot point here.  In this case we're not the ones designing the API, ARM is.  SIMDe just implements it.  Since `void*` would accept a superset of what `T*` does now there are no major backwards-compatibility concerns here, but depending on this change would mean that you would end up with errors when compiling the code on a platform which supports NEON natively.

You could try taking it up with ARM, but even if you do get someone to listen I doubt you'll have much success.  NEON supports unaligned loads and stores on AArch64 and I *think* ARMv8, but not on ARMv7… just like SIMDe doesn't want friction between SIMDe and other implementations, I doubt ARM would be keen to add unnecessary friction between ISA versions.  ARM has also really leaned into working inside of the type system for NEON, so my guess is that they wouldn't want to opt out of it by default.
